// Keep the entries sorted. Put the longest entries first because we iterate
// over them in this order. And we want, for example, '職業四段' to be
// translated as '4p', not as '職業四dan'.

const textReplacements = {
    "非即时对局，在发出请求后，对方如果在三天内没有响应，对局邀请自动关闭。": "For non-real-time games, after the request is made, if the opponent does not respond within three days, the game request will be automatically closed.",
    "限制时间的对局邀请，对方如果在10分钟内没有响应，对局邀请自动关闭。": "For a time-limited game request, if the opponent does not respond within 10 minutes, the game request will be automatically closed.",
    "银卡以上会员将会统计会员在每本棋书中的做题数量/正确率信息。": "Silver card members or above get correct-rate statistics for each book.",
    "黑先，利用先手救回带三角黑棋。提示: 第1步，找到先手。": "Black to play, using the first move to save marked stones. Hint: Step 1, find the first move.",
    "设置每道题目的做题次数，达到这个次数没有做对则判错": "Set the number of attempts for each problem. If this number is reached, it will be judged wrong.",
    "角上和边线上的棋子在出头时常用的手段你都学会了么": "Have you learned the common tactics used on the corners and sides",
    "约定时间的对局，在对局开始前没有响应则自动关闭。": "The game at the appointed time will be automatically closed if there is no response before the game starts.",
    "每道题目的做题次数，达到这个次数没有做对则判错": "The number of attemps for each problem. If this number is reached, it will be judged wrong.",
    "打开题目，思考一段时间才能落子（只对会员有效）": "You can think for a while before deciding (only possible for members)",
    "黑先，白三角是错着，请黑棋下出正确的应对。": "Black to play, the white triangle was a mistake, please make the correct response.",
    "高手！我对你的景仰犹如滔滔江水，连绵不绝": "Master! My admiration for you is like a surging river, endless",
    "一次生成的题目数量，最多不超过50道。": "You cannot generate more than 50 problems at once.",
    "在选点中选择最佳的建立根据的安定下法": "Choose the best base stabilization method among the selection points",
    "此邮箱将接受激活邮件完成账号激活流程": "This email address will receive an activation email to complete the account activation process",
    "不选择，则依靠棋友当前级别自动筛选": "If you don’t choose, it will be automatically selected based on the current player level",
    "入相信你不是答错，只是手滑了对吧": "I believe that you did not answer wrong, but your hand slipped, right",
    "你的用户名和密码不符，请再试一次": "Your username and password do not match; please try again",
    "利用先手加强黑△一子，再枷吃": "Use the first move to strengthen the black △ stone, and then capture",
    "如果超过时间未做完，则本题判错": "If the time is exceeded, the problem will be judged wrong.",
    "基礎から始める 河野臨の詰碁": "Kono Rin’s tsumego starting from the basics",
    "本题为选择题，请选择一个选项": "This question is multiple choice, please select one option",
    "白棋如何逃出被切断的两个白子?": "How does White escape from the cut off two white stones?",
    "单位为天，每多少天一次作业": "How often to run the job, in days",
    "和我相关的101棋友动作": "101weiqi Friends’ Actions Related to Me",
    "请找出此局面下的最佳一手": "Please find the best move in this situation",
    "请直接用鼠标在棋盘上落子": "Use the mouse to play stones",
    "帅！答对了这么难的题目": "Beautiful! Answering such a difficult question correctly",
    "棋怎样走才能有效地连接": "How does Black move to connect effectively",
    "101本月错题统计分析": "Community error report this month",
    "101年度错题统计分析": "Community mistakes report",
    "创建一个围棋教室/棋社": "Create a Go classroom/club",
    "不选择，则混合各种题型": "If you don’t choose, problem categories will be mixed",
    "围棋死活辞典-濑越宪作": "Life-and-Death Dictionary (Segoe Kensaku)",
    "只有一次提交解答的机会": "Only one opportunity to submit answer",
    "只有2次提交解答的机会": "Only two opportunities to submit answers",
    "请按照顺序在棋盘上落子": "Please play the moves in order",
    "设置每道题目的做题次数": "Set the number of opportunities for each problem",
    "设置每道题目的做题时间": "Set the time limit for each problem",
    "银冈棋院官子手筋习题集": "Yingang Go Academy Endgame Tesuji Problems",
    "我的本月错题统计分析": "Stats of my mistakes this month",
    "我的年度错题统计分析": "Stats of my mistakes this year",
    "打印功能只对会员开放": "The printing function is only available to members",
    "落子确认关闭中，开启": "Toggle move confirmation",
    "101棋友最近活动": "101weiqi friends recent activity",
    "对方接受后开始对局": "After the opponent accepts, the match begins",
    "按棋书章节顺序做题": "Book chapter order",
    "黑棋能否征死白子？": "Can Black kill White?",
    "围棋教室/棋社列表": "Go classroom/club list",
    "围棋闯关-棋力测试": "Go Strength Test",
    "李昌镐精讲围棋死活": "Lee Chang-ho Selected Life-and-Death Problems",
    "李昌镐精讲围棋手筋": "Lee Chang-ho Selected Tesuji Problems",
    "围棋教室/棋社动态": "News",
    "一次生成的题目数量": "Number of questions generated at a time",
    "请直接在棋盘上落子": "Play directly on the board",
    "贡献较多的棋友名单": "Top contributors",
    "围棋死活1000题": "Weiqi Life-and-Death 1000 Problems",
    "使用围豆进行提问": "Ask using Weidou",
    "我最近阅读的棋书": "Books I’ve recently read",
    "创建新的作业模板": "Create a new job template",
    "还没有101帐号": "Don’t have a 101 account yet",
    "一人使用一半时间": "Each player uses half the time",
    "官子大全官子手筋": "Endgame Encyclopedia - Tesuji",
    "生成作业打印页面": "Generate print page",
    "围棋考试/挑战赛": "Go exam/challenge",
    "Master棋谱": "MasterGo",
    "我的作业模板列表": "My job template list",
    "次提交解答的机会": "opportunities to submit answers",
    "101棋谱库研究": "Repository research",
    "设置比赛计时范围": "Set the game time range",
    "系统自动生成作业": "The system automatically generates homework",
    "应该采取本图下法": "The following method should be adopted",
    "请挡住白棋的出头": "block white's move",
    "围棋知识点专辑": "Categories list",
    "长时间包干比赛": "Correspondence game",
    "创建新作业模板": "Create a new job template",
    "问道解惑讨论区": "Discussion Forum",
    "不接受对弈邀请": "Do not accept game requests",
    "生成一份新作业": "Generate a new assigment",
    "棋 力 测 试": "Go Strength Test",
    "按难度顺序选题": "in order of difficulty",
    "李昌镐官子技巧": "Lee Chang-ho’s Endgame Skills",
    "下 一 定 式": "Next joseki",
    "一次选择的机会": "One chance to choose",
    "参与的话题列表": "participated topic list",
    "上 一 定 式": "Previous joseki",
    "本题超时未通过": "Problem failed by timeout",
    "从错题本中删除": "Remove from mistakes book",
    "瞄准对方的弱点": "Target the opponen’s weakness",
    "尚未完成的作业": "Unfinished homework",
    "101围棋网": "101 Go Net",
    "所有编辑记录": "All edit records",
    "平均做题时间": "Average problem time",
    "围棋基本技能": "Basic Go skills",
    "围棋基本手筋": "Basic tesuji",
    "成为银卡会员": "Become a Silver member",
    "黑先最佳着手": "Black to play best move",
    "棋盘大小分类": "Board size classification",
    "我收藏的题目": "Bookmarked problems",
    "悬赏题目分享": "Bounty topic",
    "棋友证书列表": "Certificate list",
    "选择一个选项": "Choose an option",
    "围棋经典手筋": "Classic tesuji",
    "围棋教室棋社": "Classroom club",
    "点击升级会员": "Click to upgrade membership",
    "围棋综合手筋": "Comprehensive tesuji",
    "创建我的私有": "Create my private",
    "段位题目分类": "Dan-level classification",
    "错题详细统计": "Detailed mistake statistics",
    "被淘汰的答案": "Eliminated answer",
    "条答案被淘汰": "eliminated answers",
    "邮箱/用户名": "email / username",
    "官子题目列表": "Endgame list",
    "围棋快速练习": "Go Quick Practice",
    "隐藏题目审核": "Hidden review",
    "系统随机选题": "in random order",
    "属于正解答案": "is a correct answer",
    "属于失败答案": "is a failure answer",
    "属于变化答案": "is a variation answer",
    "作业生成时间": "Job generation time",
    "级位题目分类": "Kyu-level classification",
    "上次阅读位置": "Last read position",
    "围棋死活形状": "Life-and-death shapes",
    "小棋仙训练营": "Little Go Fairy Training Camp",
    "发出约战请求": "Make a game request",
    "大师的下一手": "Master’s next move",
    "我收藏的棋书": "My favorite Go book",
    "我的作业列表": "My homework list",
    "我的作业统计": "My homework stats",
    "我的分享题目": "My sharing topic",
    "中国古棋规则": "Old Chinese rules",
    "其他分类题目": "Other classification",
    "其他地区棋手": "Other players",
    "个人信息设置": "Personal information settings",
    "打印题目选择": "Print problems selection",
    "本题已经通过": "Problem passed",
    "做题形式设置": "Problem settings form",
    "做题时间设置": "Question time setting",
    "级位段位证书": "rank level certificates",
    "播放演进过程": "Replay moves",
    "选择棋书章节": "Select a book chapter",
    "棋形题目搜索": "Shape search",
    "围棋手筋辞典": "Tesuji Dictionary",
    "题目名称搜索": "Title search",
    "在101工作": "Work at 101",
    "Zero棋谱": "ZeroGo",
    "黑贴6目半": "6.5 points komi",
    "黑贴7目半": "7.5 points komi",
    "抱吃和包吃": "Atari and capture",
    "大眼杀小眼": "Big eye kills small eye",
    "可立即落子": "Can be placed immediately",
    "中国流布局": "Chinese opening",
    "按难度选择": "Choose by difficulty",
    "正 确 率": "Correct rate",
    "请断开白棋": "Disconnect white",
    "人生十八局": "Eighteen rounds of life",
    "有眼杀无眼": "Eye/no eye",
    "收藏本棋书": "Favorite this book",
    "藤泽库之助": "Fujisawa Hosai",
    "下棋等级分": "Go rating points",
    "布局猜子题": "Guess opening moves",
    "桥本宇太郎": "Hashimoto Utaro",
    "棋魂之棋谱": "Hikaru No Go",
    "最后回复人": "last reply",
    "中盘作战题": "Middle game problems",
    "条修改记录": "Modification records",
    "我的收藏本": "My collection",
    "我的错题本": "My mistakes book",
    "我的记谱本": "My notation book",
    "我的作业本": "My task book",
    "枷吃和夹吃": "Net",
    "下 一 题": "Next problem",
    "最多不超过": "No more than",
    "非即时对弈": "non-real-time games",
    "请救活黑棋": "Please save black",
    "高权限棋友": "Power users",
    "上 一 题": "Previous problem",
    "本题未通过": "Problem failed",
    "本题收录于": "Problem is included in",
    "做一题设置": "Problem setup",
    "注册新用户": "Register a new user",
    "复盘挑战赛": "Replay challenge",
    "救回带三角": "Save triangle",
    "按顺序选择": "Select in order",
    "短时间比赛": "Short game",
    "道类似题目": "similar topics",
    "统计截止于": "Statistics as of",
    "今日排行榜": "Today’s Leaderboard",
    "题目知识点": "Topic category",
    "两扳长一气": "Two hane for one liberty",
    "不限制时间": "unlimited time",
    "最多75题": "Up to 75 problems",
    "微信公众号": "WeChat public account",
    "作业本名称": "Workbook name",
    "山田规三生": "Yamada Kimio",
    "一一妙手": "1-1 point",
    "一二妙手": "1-2 point",
    "三三定式": "3-3 point joseki",
    "小目定式": "3-4 point joseki",
    "目外定式": "3-5 point joseki",
    "三六定式": "3-6 point joseki",
    "高目定式": "4-5 point joseki",
    "四六定式": "4-6 point joseki",
    "職業四段": "4p",
    "五五定式": "5-5 point joseki",
    "七路全局": "7x7 whole board",
    "九路全局": "9x9 whole board",
    "关于围豆": "About Weidou",
    "添加评论": "Add comment",
    "全部对局": "All games",
    "全部题型": "All problem types",
    "已经取消": "Already cancelled",
    "今日抢答": "Answer today",
    "自动生成": "Automatically generated",
    "平均难度": "Average difficulty",
    "淡路修三": "Awaji Shuzo",
    "基础死活": "Basic life-and-death",
    "北京时间": "Beijing time",
    "盘角曲四": "Bent 4 in the corner",
    "黑白选择": "Black and white option",
    "棋盘大小": "Board size",
    "收藏此题": "Bookmark problem",
    "闯下一关": "Break the next level",
    "再次闯关": "Break through again",
    "吃子题目": "Capture",
    "吃子方向": "Capture direction",
    "打二还一": "Capture two recapture one",
    "请吃白棋": "Capture white",
    "棋盘居中": "Center board",
    "中国棋手": "Chinese players",
    "中国规则": "Chinese rules",
    "清除全部": "Clear all",
    "清除错题": "Clear mistaken questions",
    "今日完成": "Completed today",
    "完成时间": "Completion date",
    "正解答案": "Correct answers",
    "题目数量": "Count",
    "龟不出头": "Crane’s nest",
    "每日八题": "Daily 8 problems",
    "当湖十局": "Danghu Ten Bureau",
    "作业难度": "Difficulty",
    "难度范围": "Difficulty range",
    "编辑记录": "Edit record",
    "官子题目": "Endgame",
    "逃子方向": "Escape direction",
    "围棋闯关": "Exam",
    "闯关失败": "Failed to break through",
    "失败答案": "Failure answers",
    "寻找根据": "Find base",
    "查找棋友": "Find friends",
    "五目死活": "Five-point life-and-death",
    "忘记密码": "Forgot password",
    "四目死活": "Four-point life-and-death",
    "藤泽秀行": "Fujisawa Shuko",
    "对弈规则": "Game rules",
    "生成棋书": "Generate Go book",
    "生成新的": "Generate new",
    "玄玄棋经": "Gengen Gokyo",
    "棋盘风格": "Go board style",
    "围棋裁判": "Go referee",
    "棋经众妙": "Gokyo Shumyo",
    "金鸡独立": "Golden rooster",
    "谷歌围棋": "Google",
    "成长足迹": "Growth Footprint",
    "羽根直树": "Hane Naoki",
    "羽根泰正": "Hane Yasumasa",
    "帮助中心": "Help center",
    "隐藏评价": "Hide review",
    "最高难度": "Highest difficulty",
    "彦坂直人": "Hikosaka Naoto",
    "我的首页": "Home",
    "今村俊也": "Imamura Toshiya",
    "答案有误": "is a mistaken answer",
    "石田芳夫": "Ishida Yoshio",
    "井山裕太": "Iyama Yuta",
    "日本古典": "Japanese classic",
    "日本棋手": "Japanese players",
    "日韩规则": "Japanese/Korean rules",
    "作业日期": "Job date",
    "作业列表": "Job list",
    "作业模板": "Job template",
    "定式大全": "Joseki encyclopedia",
    "加藤正夫": "Kato Masao",
    "继续做题": "Keep doing problems",
    "小林光一": "Kobayashi Koichi",
    "小松英树": "Komatsu Hideki",
    "韩国棋手": "Korean players",
    "天梯训练": "Ladder training",
    "最后一手": "last move",
    "最近对局": "latest games",
    "最低难度": "Lowest difficulty",
    "前田陈尔": "Maeda Nobuaki",
    "发出请求": "Make request",
    "错题统计": "Mistake statistics",
    "修改类型": "Modification type",
    "老鼠偷油": "Mouse stealing oil",
    "向井千瑛": "Mukai Chiaki",
    "我生成的": "My generated",
    "无需等待": "No need to wait",
    "一次读秒": "One byo-yomi period",
    "一次机会": "one chance",
    "布局基础": "Opening basics",
    "普通会员": "Ordinary member",
    "大竹英雄": "Otake Hideo",
    "闯关通过": "Pass through",
    "个人信息": "Personal information",
    "错题打印": "Print mistaken questions",
    "打印题目": "Print problems",
    "做题等级": "Problem grade",
    "题库状态": "Problem library state",
    "做题次序": "Problem order",
    "题目质量": "Problem quality",
    "题目范围": "Problem scope",
    "做题设置": "Problem settings",
    "做题机会": "Problem solving opportunities",
    "做题数据": "Problem statistics",
    "购买记录": "Purchase history",
    "做题记录": "Question record",
    "题目审核": "question review",
    "做题时间": "Question time",
    "黄莺扑蝶": "Raccoon belly",
    "最近棋谱": "Recent games",
    "重做设置": "Redo settings",
    "取消收藏": "Remove bookmark",
    "重设密码": "Reset password",
    "闯关结果": "Results",
    "错题重做": "Rework mistakes",
    "旋转棋盘": "Rotate board",
    "坂田荣男": "Sakata Eio",
    "濑越宪作": "Segoe Kensaku",
    "标注难度": "Set difficulty",
    "七死八活": "Seven die, eight live",
    "棋形搜索": "Shape search",
    "题目搜索": "Shape search",
    "分享本题": "Share this question",
    "显示答案": "Show answers",
    "立即注册": "Sign up now",
    "简单官子": "Simple endgame",
    "六目死活": "Six-point life-and-death",
    "专项训练": "Special training",
    "滚打包收": "Squeeze",
    "开始做题": "Start problems",
    "开始时间": "start time",
    "起始时间": "Start time",
    "开始解答": "Start to answer",
    "作业状态": "State",
    "棋力检测": "Strength detection",
    "棋力测试": "Strength Test",
    "提交答案": "Submit answer",
    "闯关成功": "Successfully passed the barrier",
    "左右同型": "Symmetrical shape",
    "左右同形": "Symmetrical shape",
    "高尾绅路": "Takao Shinji",
    "武宫正树": "Takemiya Masaki",
    "思考时间": "Thinking time",
    "三目死活": "Three-point life-and-death",
    "时间限制": "Time limit",
    "每方用时": "Time per player",
    "时间设定": "Time settings",
    "题目搜索": "Topic search",
    "骗招题目": "Trick plays",
    "两次机会": "two chances",
    "更新时间": "update time",
    "变化答案": "Variation answers",
    "微信登录": "WeChat login",
    "微信扫码": "WeChat scan code",
    "山下敬吾": "Yamashita Keigo",
    "安井算知": "Yasui Sanchi",
    "依田纪基": "Yoda Norimoto",
    "涛哥十佳": "Yu Qingquan top 10",
    "加入时间": "Join time",
    "请吃△子": "Capture △",
    "第十一": "11th",
    "11路": "11x11",
    "第十二": "12th",
    "第十三": "13th",
    "13路": "13x13",
    "第十四": "14th",
    "第十五": "15th",
    "第十六": "16th",
    "第十七": "17th",
    "第十八": "18th",
    "第十九": "19th",
    "19路": "19x19",
    "修改后": "After modification",
    "解答中": "Answering",
    "攻之部": "Attack section",
    "修改前": "Before modification",
    "大事典": "Big Encyclopedia",
    "大猪嘴": "Big pig snout / J-group",
    "训练营": "Camp",
    "不能救": "Can’t save",
    "曹大元": "Cao Dayuan",
    "吃子题": "Capture problem",
    "对杀题": "Capturing race problem",
    "金柜角": "Carpenter’s square",
    "知识点": "Category",
    "陈祖德": "Chen Zude",
    "赵治勋": "Cho Chikun",
    "赵汉乘": "Cho Han-seung",
    "曹薰铉": "Cho Hun-hyeon",
    "崔哲瀚": "Choi Cheol-han",
    "崔明勋": "Choi Myeong-hun",
    "选择选": "choose",
    "已完成": "Completed",
    "接不归": "Connect and die",
    "模仿题": "Copying problem",
    "角之部": "Corner section",
    "正确率": "Correct rate",
    "正确率": "Correct rate",
    "刚创建": "Created",
    "创 建": "Creation",
    "发起人": "creator",
    "相思断": "Crosscut",
    "死之部": "Death section",
    "的方向": "direction",
    "正在做": "Doing",
    "做一题": "Done problem",
    "连环劫": "Double Ko",
    "官子题": "Endgame problem",
    "范西屏": "Fan Xiping",
    "范蕴若": "Fan Yunruo",
    "讨论区": "Forum",
    "吴清源": "Go Seigen",
    "古灵益": "Gu Lingyi",
    "天龙图": "Heavenly Dragons",
    "我执黑": "I am black",
    "我执白": "I am white",
    "进行中": "in process",
    "江维杰": "Jiang Weijie",
    "定式题": "Joseki problem",
    "姜东润": "Kang Dong-yun",
    "官子谱": "Kanzufu",
    "片冈聪": "Kataoka Satoshi",
    "金志锡": "Kim Ji-seok",
    "木谷实": "Kitani Minoru",
    "劫之部": "Ko section",
    "小林觉": "Kobayashi Satoru",
    "排行榜": "Leaderboard",
    "李昌镐": "Lee Chang-ho",
    "李世石": "Lee Se-dol",
    "李钦诚": "Li Qincheng",
    "李轩豪": "Li Xuanhao",
    "廖元赫": "Liao Yuanhe",
    "生之部": "Life section",
    "死活题": "Life-and-death problem",
    "罗洗河": "Luo Xihe",
    "马晓春": "Ma Xiaochun",
    "孟泰龄": "Meng Tailing",
    "芈昱廷": "Mi Yuting",
    "修改于": "modified on",
    "睦镇硕": "Mok Jin-seok",
    "下一页": "Next page",
    "下一题": "Next problem",
    "聂卫平": "Nie Weiping",
    "无棋子": "No stone",
    "回贴数": "number of replies",
    "王铭琬": "O Meien",
    "王立诚": "O Rissei",
    "公开赛": "Open",
    "布局题": "Opening problem",
    "白洪淅": "Paek Hong-suk",
    "朴廷桓": "Park Jung-hwan",
    "朴永训": "Park Yeong-hun",
    "待审核": "pending review",
    "彭立尧": "Peng Liyao",
    "朴文垚": "Piao Wenyao",
    "练习册": "Practice book",
    "上一页": "Previous page",
    "上一题": "Previous problem",
    "题开始": "problem onwards",
    "习题集": "Problem set",
    "公众号": "Public account",
    "钱宇平": "Qian Yuping",
    "记住我": "Remember me",
    "林海峰": "Rin Kaiho",
    "芮乃伟": "Rui Naiwei",
    "酒井猛": "Sakai Takeshi",
    "徐奉洙": "Seo Bong-soo",
    "施襄夏": "Shi Ding’an",
    "柳时熏": "Shikun Ryu",
    "申真谞": "Shin Jin-seo",
    "边之部": "Side section",
    "小猪嘴": "Small pig snout",
    "胀牯牛": "Squash (Oshi-Tsubushi)",
    "星定式": "Star-point joseki",
    "大头鬼": "Stone tower",
    "高川格": "Takagawa Kaku",
    "唐韦星": "Tang Weixing",
    "手筋题": "Tesuji problem",
    "童梦成": "Tong Mengcheng",
    "柁嘉熹": "Tuo Jiaxi",
    "盘龙眼": "Two-headed dragon",
    "倒脱靴": "Under the stones",
    "上一步": "Undo move",
    "不限制": "unlimited",
    "用户名": "Username",
    "验证码": "Verification code",
    "第一卷": "Volume 1",
    "第二卷": "Volume 2",
    "第三卷": "Volume 3",
    "第四卷": "Volume 4",
    "第五卷": "Volume 5",
    "第六卷": "Volume 6",
    "王楚轩": "Wang Chuxuan",
    "元晟溱": "Weon Seong-jin",
    "谢依旻": "Xie Yimin",
    "山城宏": "Yamashiro Hiroshi",
    "伊凌涛": "Yi Lingtao",
    "刘昌赫": "Yu Ch’ang-hyeok",
    "结城聪": "Yuki Satoshi",
    "周睿羊": "Zhou Ruiyang",
    "接触战": "Contact fight",
    "慢一气": "Slow down",
    "第十": "10th",
    "第一": "1st",
    "第二": "2nd",
    "第三": "3rd",
    "第四": "4th",
    "第五": "5th",
    "5路": "5x5",
    "第六": "6th",
    "第七": "7th",
    "7路": "7x7",
    "第八": "8th",
    "第九": "9th",
    "9路": "9x9",
    "约战": "About",
    "添加": "Add",
    "高级": "Advanced",
    "应对": "Answer",
    "解答": "Answer",
    "答案": "answers",
    "擂台": "Arena",
    "攻击": "Attack",
    "头像": "Avatar",
    "平均": "Average",
    "基本": "basic",
    "得益": "benefit",
    "黑子": "Black stone",
    "黑子": "Black stone",
    "黑先": "Black to play",
    "盲点": "Blind spot",
    "棋书": "Books",
    "购买": "Buy",
    "能救": "Can save",
    "取消": "Cancel",
    "不能": "Cannot",
    "吃子": "Capture",
    "门吃": "Capture by atari",
    "被吃": "captured",
    "对杀": "Capturing race",
    "证书": "Certificate",
    "应战": "Challenge",
    "常昊": "Chang Hao",
    "章节": "chapter",
    "关卡": "Checkpoint",
    "陳禧": "Chen Xi",
    "陈贤": "Chen Xian",
    "张栩": "Cho U",
    "崔精": "Choi Jeong",
    "关闭": "Close",
    "专栏": "Column",
    "评论": "Comment",
    "解说": "Commentary",
    "全集": "Complete Works",
    "恭喜": "Congratulations",
    "连接": "Connect",
    "联络": "Connection",
    "做对": "Correct",
    "正确": "Correct",
    "正解": "correct",
    "創作": "creation",
    "切断": "Cut",
    "删除": "Delete",
    "破眼": "Destroying eyes",
    "词典": "dictionary",
    "难度": "Difficulty",
    "丁浩": "Ding Hao",
    "做题": "Do problems",
    "双打": "Double atari",
    "每次": "Each",
    "每题": "Each question",
    "编辑": "Edit",
    "初级": "Elementary",
    "邮箱": "Email",
    "官子": "Endgame",
    "启蒙": "Enlightenment",
    "逃子": "Escape",
    "兑换": "Exchange",
    "退出": "Exit",
    "研究": "Explore",
    "失败": "fail",
    "名家": "Famous",
    "最快": "Fastest",
    "最后": "Final",
    "完成": "finished",
    "上卷": "First volume",
    "补棋": "Fix the shape",
    "频率": "Frequency",
    "从第": "From",
    "藤泽": "Fujisawa",
    "对弈": "Game",
    "入门": "Getting started",
    "围棋": "Go",
    "棋理": "Go reasoning",
    "获得": "Got",
    "获得": "Got",
    "古力": "Gu Li",
    "猜先": "Guess colors (nigiri)",
    "隐藏": "hide",
    "作业": "Homework",
    "道策": "Honinbo Dosaku",
    "丈和": "Honinbo Jowa",
    "秀榮": "Honinbo Shuei",
    "秀甫": "Honinbo Shuho",
    "秀哉": "Honinbo Shusai",
    "秀策": "Honinbo Shusaku",
    "秀和": "Honinbo Shuwa",
    "小时": "hour",
    "初始": "Initial",
    "中级": "Intermediate",
    "判断": "Judgement",
    "柯洁": "Ke Jie",
    "聚杀": "Killing",
    "打劫": "Ko",
    "孔杰": "Kong Jie",
    "韩国": "Korea",
    "征子": "Ladder",
    "下卷": "Last volume",
    "级别": "Level",
    "李喆": "li Zhe",
    "连笑": "Lian Xiao",
    "题库": "Lib",
    "延气": "Liberty extending",
    "紧气": "Liberty filling",
    "死活": "life-and-death",
    "限时": "limit",
    "列表": "list",
    "维护": "maintenance",
    "做眼": "Making eyes",
    "方法": "method",
    "中卷": "Middle volume",
    "分钟": "minutes",
    "错误": "Mistake",
    "修改": "Modify",
    "月度": "Monthly",
    "更多": "More",
    "早上": "morning",
    "我的": "My",
    "名称": "name",
    "净死": "Net death",
    "晚上": "night",
    "记谱": "Notation",
    "注意": "Notice",
    "手数": "number of moves",
    "确定": "OK",
    "只有": "Only",
    "部分": "Part",
    "密码": "Password",
    "密码": "password",
    "对战": "Play",
    "帖子": "Posts",
    "练习": "practice",
    "私信": "Private messages",
    "問題": "problem",
    "问题": "problem",
    "题型": "Problem type",
    "道题": "problems",
    "数量": "Quantity",
    "评分": "Rating",
    "充值": "Recharge",
    "棋谱": "Records",
    "精解": "refinement",
    "剩余": "Remaining",
    "审核": "review",
    "评价": "Review",
    "腾挪": "Sabaki",
    "弃子": "Sacrifice",
    "保存": "Save",
    "得分": "Score",
    "秒钟": "seconds",
    "双活": "Seki",
    "先手": "sente",
    "编号": "Serial number",
    "整形": "Shape",
    "棋形": "Shape",
    "时越": "Shi Yue",
    "显示": "show",
    "登录": "Sign in",
    "签到": "Sign in",
    "注册": "Sign up",
    "技巧": "Skill",
    "倒扑": "Snapback",
    "扑吃": "Snapback capture",
    "状态": "state",
    "小类": "subcategories",
    "提交": "submit",
    "提供": "supplier",
    "标签": "Tags",
    "檀啸": "Tan Xiao",
    "脱先": "Tenuki",
    "手筋": "Tesuji",
    "思考": "think",
    "用时": "Time spent",
    "超时": "Timeout",
    "提示": "Tips",
    "题目": "Topic",
    "总数": "Total",
    "试下": "Try",
    "诘棋": "tsumego",
    "类型": "Type",
    "升级": "Upgrade",
    "棋友": "Users",
    "变化": "Variation",
    "等待": "wait",
    "王檄": "Wang Xi",
    "弱点": "weakness",
    "挖吃": "Wedge",
    "围豆": "Weidou",
    "白子": "White stone",
    "白先": "White to play",
    "谢赫": "Xie He",
    "张立": "Zhang Li",
    "封锁": "Block",
    "如何": "How to",
    "打入": "Invade",
    "打吃": "Capture",
    "定形": "fix form",
    "请选": "please choose",
    "挤": "Atekomi / angle wedge",
    "碰": "Attach",
    "双": "Bamboo joint",
    "黑": "Black",
    "能": "Can",
    "夹": "Clamp",
    "集": "collection",
    "渡": "Connect underneath",
    "断": "Cut",
    "跨": "Cut across",
    "段": "dan",
    "立": "Descent, stand",
    "尖": "Diagonal",
    "长": "Extend",
    "扳": "Hane",
    "有": "has",
    "顶": "Hitting on the head",
    "飞": "Knight’s move",
    "劫": "Ko",
    "级": "kyu",
    "活": "life",
    "分": "min",
    "错": "mistaken",
    "枷": "Net",
    "网": "network",
    "跳": "One point jump",
    "点": "Placement",
    "题": "problem",
    "逆": "reverse",
    "对": "right",
    "秒": "sec",
    "扑": "Throw-in",
    "虎": "Tiger’s mouth",
    "托": "Underneath attachment",
    "卷": "volume",
    "挖": "Wedge",
    "白": "White",
    "胜": "win",
    "杀": "kill",
    "答": "answer",
}

// cache regular expressions
let re_problem_number = /第\s*(\d+)\s*题/;
let re_date = /(20\d\d)年(\d\d?)月(\d\d?)日/;
let re_part_number = /第\s*(\d+)\s*部分/;
let re_questions_in_total = /共\s*(\d+)\s*道题目/;
let re_min_limit = /限制(\d+)分钟/;
let re_times = /为(\d+)次/;
let re_every_n_days = /每(\d+)天一次/;

const imageReplacements = {
    'https://static2.101weiqi.com/static/images/home/home1.png': 'http://baniverso.com/101weiqiLocalizer/img/home1.png',
    'https://static2.101weiqi.com/static/images/home/home2.png': 'http://baniverso.com/101weiqiLocalizer/img/home2.png',
    'https://static2.101weiqi.com/static/images/home/home3.png': 'http://baniverso.com/101weiqiLocalizer/img/home3.png',
    'https://static2.101weiqi.com/static/images/home/home4.png': 'http://baniverso.com/101weiqiLocalizer/img/home4.png',
    'https://static2.101weiqi.com/static/images/home/home5.png': 'http://baniverso.com/101weiqiLocalizer/img/home5.png',
    'https://static2.101weiqi.com/static/images/home/home6.png': 'http://baniverso.com/101weiqiLocalizer/img/home6.png',
    'https://static2.101weiqi.com/static/images/home/home10.png': 'http://baniverso.com/101weiqiLocalizer/img/home10.png',
    'https://static2.101weiqi.com/static/images/home/home12.png': 'http://baniverso.com/101weiqiLocalizer/img/home12.png',
    'https://static2.101weiqi.com/static/images/home/home20.png': 'http://baniverso.com/101weiqiLocalizer/img/home20.png',
    'https://static2.101weiqi.com/static/images/home/home21.png': 'http://baniverso.com/101weiqiLocalizer/img/home21.png',
    'https://static2.101weiqi.com/static/images/home/home88.png': 'http://baniverso.com/101weiqiLocalizer/img/home88.png',
    'https://static2.101weiqi.com/static/images/home/home100.png': 'http://baniverso.com/101weiqiLocalizer/img/home100.png',
}

recursiveReplace(document.body)
replaceAttributes()
replaceImageSources(document.body)

let observer = new MutationObserver(mutationRecords => {
    mutationRecords.forEach(m => {
        if (m.type == 'characterData') {
            observer.disconnect()    // avoid infinite loops
            m.target.nodeValue = replaceInString(m.target.nodeValue)
            observe()
        } else if (m.type == 'childList') {
            observer.disconnect()    // avoid infinite loops
            m.addedNodes.forEach(node => recursiveReplace(node))
            observe()
        } else if (m.type == 'attributes') {
            observer.disconnect()    // avoid infinite loops

            switch(m.attributeName) {
                case "label":
                    m.target.label = replaceInString(m.target.label)
                    break;
                case "title":
                    m.target.title = replaceInString(m.target.title)
                    break;
            }

            observe()
        }
    })
})

const observe = () => {
    observer.observe(document, {
        characterData: true,
        childList: true,
        subtree: true,
        attributeFilter: [ "label", "title" ],
    });
}

observe()

/*
    Recurse through DOM elements.  If element is a text element process it, otherwise recurse.
*/
function recursiveReplace(node) {
    if (node.nodeType == 3 && node.nodeName != 'SCRIPT') {
        node.nodeValue = replaceInString(node.nodeValue)
    } else if (node.nodeType == 1 && node.nodeName != 'SCRIPT' && node.nodeName != 'STYLE') {
        var child = node.firstChild;
        while (child) {
        	recursiveReplace(child);
        	child = child.nextSibling;
        }
    }
}

function replaceInString(s) {
    // non-fixed strings
    s = s.replace(re_date, (match, year, month, day) => [ year, month, day ].join('.'))
    s = s.replace(re_problem_number, (match, number) => `Problem ${number}`)
    s = s.replace(re_part_number, (match, number) => `Part ${number}`)
    s = s.replace(re_questions_in_total, (match, number) => `${number} questions in total`)
    s = s.replace(re_min_limit, (match, limit) => `${limit} min limit`)
    s = s.replace(re_times, (match, times) => `${times} times`)
    s = s.replace(re_every_n_days, (match, n) => `Every ${n} days`)

    for (const [key, value] of Object.entries(textReplacements)) {
        // add a space because Chinese doesn't have spaces
        s = s.replace(key, ' ' + value + ' ')
    }
    return s
}

function replaceAttributes() {
    document.querySelectorAll('[label]').forEach((el) => {
        el.label = replaceInString(el.label)
    })
    document.querySelectorAll('[title]').forEach((el) => {
        el.title = replaceInString(el.title)
    })
}

function replaceImageSources(node) {
    node.querySelectorAll('img').forEach(img => {
        for (const [key, value] of Object.entries(imageReplacements)) {
            img.src = img.src.replace(key, value)
        }
    })
}
